In [8]:

# To get all V1 voxel responses in the training data set:
import pandas as pd
import tables,numpy
f = tables.open_file('EstimatedResponses.mat')
f.list_nodes # Show data file structure with all variables available
Dat = f.get_node('/dataTrnS1')[:] #get the response data for all voxels and all images #TrnS1 - 5 training runs for subject 1
ROI = f.get_node('/roiS1')[:].flatten() #get the ROI info for subject 1
V1idx = numpy.nonzero(ROI==1)[0] #returns the indices for when ROI == 1 (V1 region)
V1resp = Dat[:,V1idx] # get all rows, but only those voxels (columns) corresponding to a region of interest (V1)

In [28]:
V1resp

array([[ 0.81356815,  0.80712882, -1.04932228, ...,  0.59989749,
        -0.1908697 , -0.990639  ],
       [-0.89468871, -1.6246709 , -0.44189263, ...,  0.28144435,
        -0.1197159 , -0.34948287],
       [-1.12824869, -0.07142458,  0.36138328, ...,  0.79869637,
         0.24981265,  1.79075909],
       ...,
       [-0.51093255,  1.55392352, -0.51422032, ...,         nan,
                nan,         nan],
       [-1.08626526, -1.14839827, -0.41331365, ...,         nan,
                nan,         nan],
       [ 1.06931569,  0.44068302, -0.06721221, ...,         nan,
                nan,         nan]])

In [26]:
Dat.shape # (1750, 25915) --> each row corresponds to a response for each training image, 
                            # each column represents a response in a given voxel
Dat
# Dat_df = pd.DataFrame(Dat)
# Dat_df

array([[ 0.24648143, -0.93649976, -1.19105311, ...,  0.90839118,
        -0.84117486, -1.36433012],
       [ 1.77459505, -0.5922482 ,  0.61484651, ..., -0.52150544,
         0.00790187, -0.77095919],
       [-0.7453231 ,  0.4838647 ,  1.22817282, ...,  0.14629002,
        -0.76814534, -0.49050971],
       ...,
       [ 0.29343167,  0.42033294, -0.2035856 , ...,         nan,
                nan,         nan],
       [ 1.19153643,  0.70607336,  0.85566766, ...,         nan,
                nan,         nan],
       [-0.16773532,  0.27454646,  0.11508219, ...,         nan,
                nan,         nan]])

In [17]:
ROI #classifies each of the 25k voxels with an ROI label
#ROI_df = pd.DataFrame(ROI)
#ROI.shape #(25915,)


array([0., 0., 0., ..., 3., 3., 3.])

In [13]:
V1idx #gives index for 3D localization (not realy clear how it works)
#V1idx.shape #1331


array([ 4400,  4446,  4494, ..., 25801, 25802, 25820], dtype=int64)

In [41]:
V1resp_df = pd.DataFrame(V1resp)
V1resp_df

0         1         2         3         4         5         6     \
0     0.813568  0.807129 -1.049322  0.193325  1.037004  0.909314 -0.480378   
1    -0.894689 -1.624671 -0.441893 -0.502600  0.473112 -1.183671 -1.458399   
2    -1.128249 -0.071425  0.361383  0.085778 -0.370584 -0.566010  0.292175   
3    -0.668719  0.783184 -1.626778 -1.086943 -0.364778 -0.594244 -1.871174   
4    -1.701397  0.560961 -0.672416 -0.894389 -0.804314 -1.116508 -1.329612   
5     0.259927 -0.641695  1.812091  0.256199  0.855146  0.487599  0.223880   
6    -0.955879 -0.134481  0.560316  0.841305 -0.404486 -0.084624 -0.423269   
7    -1.396478  0.377208 -0.231832 -0.668628 -0.405093 -0.380912 -0.182107   
8    -0.277676  2.158916  1.447164  0.008809 -0.901599 -0.454842 -1.774547   
9     0.763283 -0.406531  0.985552 -0.300945 -1.458580 -0.002892 -2.528229   
10    0.895320  1.264048 -0.762084 -0.285875 -1.137673  0.832897 -0.559130   
11   -0.387034 -1.474703 -1.325541  0.641370  1.309175  0.238443  0.888089   
12    0.925874  2.400245  1.124176  0.122282  0.912101 -0.276968  0.435794   
13    0.571668  0.260514  1.130259  1.044742  0.151729 -0.847864 -1.645881   
14   -1.069951  0.280355  1.678617  1.034128  0.707629  1.413620  0.135255   
15    0.834410 -0.841537 -2.485438 -0.782407  0.488546  0.082304 -1.192849   
16    0.869999  1.110010 -0.213339 -0.163891 -1.875771 -1.129486 -1.460371   
17   -0.752491 -0.872505 -1.018907  1.108157  0.293421  0.382421  0.013379   
18    1.060815 -0.026006 -0.514183  1.250228  0.463633 -0.405547 -1.530340   
19   -1.317310 -1.402279 -1.479663  0.375687  0.743568 -0.223372 -1.875330   
20   -0.563254 -0.817032 -0.233257  1.710043  1.214607  0.136771  1.107127   
21   -0.276386  0.476479 -0.454163  1.319843  1.087434  1.302247  0.512789   
22   -0.034228  0.985996  0.366014  1.317537  1.679061  1.075046 -1.767752   
23   -0.456868 -0.454926 -0.234124 -0.825740 -0.937847 -0.862733  0.445113   
24    0.358241 -1.142604 -0.418973 -0.071724 -0.113901 -0.215506 -0.608629   
25    0.348465  0.895337  0.587778 -0.159624  0.149433  0.727212  0.140590   
26   -0.228868  0.014986 -0.477070 -0.005683 -0.470693 -0.472308 -1.964492   
27    0.596132  0.671528  0.665007  0.730406 -0.395828 -0.018050 -0.013850   
28   -1.168597  0.076909 -0.466651  0.216063 -0.386165 -0.624820 -0.437110   
29    0.073389  0.074626  2.264467  1.603907  0.273446  0.474039 -2.511044   
...        ...       ...       ...       ...       ...       ...       ...   
1720 -1.513087 -0.583604  0.033121  0.884212 -0.240515  0.927998  0.720951   
1721 -0.818475 -0.671531  0.557524  0.510963  1.840315  1.127179 -0.304631   
1722  0.503096  2.276224 -0.249737 -1.783186 -0.544348 -1.065093  0.475870   
1723 -2.291605 -1.826317  0.435873 -0.943979 -0.173260 -1.106566  1.276779   
1724 -1.803644 -0.363282  1.383777  1.711067  0.890470  1.805877  1.133572   
1725  1.489846 -1.071341  1.282235  0.807000  0.747817  0.870831  2.176330   
1726  1.275466  1.441012  1.116338 -0.154523  0.118525  0.822152  1.089802   
1727 -0.278405  0.816206 -0.992068 -0.252745 -1.179195 -0.905422  0.742955   
1728  1.395163  0.306039  0.158216  0.681677  0.584708 -1.047284 -0.354442   
1729 -0.730165  1.599950  0.918354 -0.756419 -1.625191  0.968529  0.391037   
1730 -0.792378 -0.701212  0.126334 -1.315149  0.599049 -0.545881 -0.184333   
1731 -0.077589 -0.103140  0.523719  0.243968  0.557244 -0.495743 -1.578122   
1732  0.094614 -0.702151 -0.778749  0.158275  1.296057  0.575236 -2.006855   
1733  1.147581  1.254064  0.575223  0.259604 -0.745847 -0.186216 -0.048653   
1734  0.785039 -1.243246  0.145358  0.787105 -0.871391 -0.062248 -0.074686   
1735  2.286224  1.566000  1.356550 -2.252308 -2.432479 -2.215578 -0.018585   
1736 -3.520334 -0.734725  1.134241 -0.469746  0.236276 -0.482614  0.151753   
1737  1.611009  0.445981 -0.165664  0.319156  0.106108 -2.633111  1.860740   
1738  0.137332 -0.783660  0.844181  0.486054 -0.390249 -1.697977  0.051110   
1739 -0.363357  0.774497 -0.5059

In [23]:
Vox_Idx = f.get_node('/voxIdxS1')[:]
Vox_Idx
#Vox_Idx.shape

array([[  657.,   715.,   716., ..., 71591., 71592., 71593.]])

In [2]:
import matplotlib.pyplot as plt
import numpy as np

#fig, plt = subplots(figsize=(18, 2))
plt.imshow(V1resp, cmap='hot', interpolation='nearest',aspect='auto')

plt.show()

NameError: name 'V1resp' is not defined

0         1         2         3         4         5         6      \
0     0.246481 -0.936500 -1.191053  0.309719 -0.408499  0.471987 -0.212231   
1     1.774595 -0.592248  0.614847 -0.342200 -0.620990 -0.388317 -0.692228   
2    -0.745323  0.483865  1.228173  1.046187 -1.055872  1.258519  0.756646   
3     0.825166  0.145755 -0.440533 -0.364821 -0.053425 -0.686088 -0.326027   
4    -0.942847 -0.722776 -0.224091 -0.795447  1.078877  0.443272 -0.038215   
5     0.285353 -0.085507  0.454944  0.129533  0.653240  0.307470  0.551851   
6    -1.475146  0.526175  0.415169  2.024743  0.853309  0.827081  0.332994   
7    -0.885851 -0.046904  1.335724 -0.832844 -0.988062 -0.153846  0.267999   
8    -0.296352 -0.748384 -1.631548  0.507282  0.623157  0.571557 -0.042114   
9     0.315938 -1.852261 -0.691844 -0.649998 -1.042157 -0.089182  0.731064   
10   -1.002625  0.739513 -0.975350 -0.370908 -1.271130 -1.308639  0.339004   
11   -0.171078 -1.632514  2.104023  0.334681  0.357935  0.654560 -0.988462   
12    0.270978  0.589001  2.740710 -1.204896  0.197646  0.189700 -1.033811   
13    0.231783  0.727446  0.643920  0.441897  0.597689 -0.631319  0.950063   
14    1.043698 -2.032256 -1.446317 -0.708204  0.126057  1.110542  0.348274   
15    0.011139 -1.086182 -2.016899 -0.035726  1.188621 -0.145649 -0.486165   
16    0.954676 -0.703822 -0.914319 -0.866345 -1.117945 -0.882579 -1.747772   
17    1.377478 -2.467318 -1.992560 -1.858686 -0.220450  0.445568  1.022432   
18    1.643509 -0.923411  0.325284  0.352457 -1.204499 -0.719650 -0.121878   
19    0.561123 -0.241065  0.324257 -1.310464 -0.449173 -0.373175 -0.164902   
20   -0.688193 -1.852386 -2.003994  0.077369  0.205371  1.432050  1.739060   
21   -0.329746 -0.695478 -0.397859 -0.440504 -1.808209  0.587733  1.266028   
22   -1.736293 -1.680420  0.432087 -0.007272 -1.635986 -0.258088  0.091729   
23    0.024049 -0.886119 -0.073000 -0.086231 -1.065110 -1.027635  0.108385   
24    0.684915 -1.150832 -0.775421 -0.476270 -1.073630  0.856830 -0.130856   
25   -0.035952 -0.100917  0.348605  0.667371  1.291911  1.123787  1.830195   
26    1.012374  0.598910  0.350824 -0.546578  1.778503  0.786854  0.377362   
27    1.274544 -0.958279  0.590903  0.061294  0.934761  0.571967  0.471150   
28    1.653313 -1.305153  0.464196 -0.178259  0.774614  1.262411 -1.504243   
29    1.310414 -1.090629 -1.521721 -0.628212 -0.656819 -0.742070  0.808293   
...        ...       ...       ...       ...       ...       ...       ...   
1720 -0.500030  1.629702  0.577782 -2.266023 -1.307172 -0.844684  0.104615   
1721 -0.146829  1.448289  0.505656 -0.453588 -1.354686 -1.697257 -0.148714   
1722 -1.940049 -0.561847 -0.098761 -0.916348 -1.254390 -0.797879 -0.266598   
1723  0.536565 -0.013665 -1.572450 -0.511781 -2.082977  1.353555  0.456207   
1724  0.061793  0.216845 -0.159955 -0.968173 -0.254499 -1.550180 -0.769610   
1725  0.579088  0.279901 -0.392681  0.977512  0.896584  0.855517  0.158602   
1726  0.035473  0.354942 -0.388330 -1.803183 -0.695261 -0.303034 -2.281876   
1727  0.299917 -0.156558 -1.175254  0.305009 -0.409543 -0.035628 -0.808087   
1728  1.124476 -0.110010  0.769514 -0.046562 -0.447849 -0.572753 -0.390061   
1729  0.127542  0.112968  0.139131 -0.749959 -0.241487  1.606995  0.998762   
1730 -0.449099  1.186358  0.077922 -2.255630 -0.707798 -0.756613 -1.219759   
1731  1.003838  1.993531 -0.131479 -0.811204 -1.344952  0.539562 -0.932414   
1732  0.411960 -0.265283  1.267288 -3.179260 -0.605826  0.072394 -0.923513   
1733 -0.205045  1.597652  0.791016 -0.971332  0.858645  1.133579 -0.158436   
1734 -0.675609  0.484047 -0.433612 -0.071172 -0.212350 -0.746093 -0.773670   
1735  0.551327 -0.211325  0.132388 -0.950367 -0.089676 -1.604731 -0.178227   
1736  0.084744 -0.411617 -0.928781 -1.522159 -0.646435 -0.043001 -0.319804   
1737  1.262854  1.617217 -1.610209  1.342249 -0.566338  1.120290 -0.050344   
1738  1.401957  0.322565  0.489708  0.586075 -1.338191 -0.059330 -0.766836   
1739 -0.643923  0.480166 -0.232